name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Menjalankan workflow saat ada push ke branch main
  pull_request:
    branches:
      - main # Menjalankan workflow saat ada pull request ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_DandiTaufiq1402 }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_DandiTaufiq1402 }}/uas-pcc-dandi_taufiqurrahman-2025:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_DandiTaufiq1402 }}/uas-pcc-dandi_taufiqurrahman-2025:latest
